def stock_list():
    data = [
        ('MMM',"MMM - 3M"),
        ('AXP',"AXP - American Express"),
        ('AAPL',"AAPL - Apple"),
        ('BA',"BA - Boeing"),
        ('CAT',"CAT - Caterpillar"),
        ('CVX',"CVX - Chevron"),
        ('CSCO',"CSCO - Cisco Systems"),
        ('KO',"KO - Coca-Cola"),
        ('DOW',"DOW - Dow Inc."),
        ('XOM',"XOM - ExxonMobil"),
        ('GS',"GS - Goldman Sachs"),
        ('HD',"HD - The Home Depot"),
        ('IBM',"IBM - IBM"),
        ('INTC',"INTC - Intel"),
        ('JNJ',"JNJ - Johnson & Johnson"),
        ('JPM',"JPM - JPMorgan Chase"),
        ('MCD',"MCD - McDonald's"),
        ('MRK',"MRK - Merck & Company"),
        ('MSFT',"MSFT - Microsoft"),
        ('NKE',"NKE - Nike"),
        ('PFE',"PFE - Pfizer"),
        ('PG',"PG - Procter & Gamble"),
        ('TRV',"TRV - Travelers"),
        ('UNH',"UNH - UnitedHealth Group"),
        ('UTX',"UTX - United Technologies"),
        ('VZ',"VZ - Verizon"),
        ('V',"V - Visa"),
        ('WMT',"WMT - Walmart"),
        ('WBA',"WBA - Walgreens Boots Alliance"),
        ('DIS',"DIS - Walt Disney"),
         ]
         
    return data